
INSERT INTO `Employment_Status` (`Status`)
VALUES
('Active'),
('Inactive'),
('On Leave'),
('Terminated'),
('Retired'),
('Suspended'),
('Probation'),
('Resigned'),
('Temporary'),
('Full-time'),
('Part-time'),
('Contractor'),
('Freelancer'),
('Consultant'),
('Intern'),
('Trainee'),
('Per Diem'),
('Seasonal'),
('Volunteer'),
('Remote'),
('Flextime'),
('Shift Worker'),
('Casual'),
('Freight'),
('Layoff'),
('Casual/Seasonal'),
('Fixed-term'),
('Self-Employed'),
('Zero Hours'),
('Other');

-- select * from Employment_Status;
