INSERT INTO `Employee_Custom_Attribute` (`Attribute_ID`, `Employee_ID`, `Value`) VALUES
(1, 1, 'Intermediate'),
(2, 2, 'Certified Scrum Master'),
(3, 3, 'English, French'),
(4, 4, 'Back-end Development'),
(5, 5, 'ACM Member'),
(6, 6, '3 years at ABC Corp.'),
(1, 7, 'Advanced'),
(2, 8, 'Certified Six Sigma Black Belt'),
(3, 9, 'English, German'),
(4, 10, 'Full-stack Development'),
(5, 11, 'IEEE Member'),
(6, 12, '4 years at DEF Ltd.'),
(1, 13, 'Intermediate'),
(2, 14, 'Certified Product Owner'),
(3, 15, 'English, Spanish'),
(4, 16, 'Database Administration'),
(5, 17, 'PMI Member'),
(6, 18, '2 years at GHI Inc.'),
(1, 19, 'Advanced'),
(2, 20, 'Certified Business Analyst'),
(3, 21, 'English, French, Spanish'),
(4, 22, 'UI/UX Design'),
(5, 23, 'ACM Member'),
(6, 24, '6 years at JKL Corp.'),
(1, 25, 'Intermediate'),
(2, 26, 'Certified Data Scientist'),
(3, 27, 'English, Chinese'),
(4, 28, 'Cloud Computing'),
(5, 29, 'IEEE Member'),
(6, 30, '4 years at MNO Ltd.');

-- select * from Employee_Custom_Attribute;
